
    spring:
      primary:
        datasource:
          url: jdbc:mysql://localhost:3306/user_local?characterEncoding=utf-8&useSSL=false&characterSetResults=utf-8&createDatabaseIfNotExist=true
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          password: 111111
      secondary:
        datasource:
#          url: jdbc:mysql://114.247.151.163:3306/eyangye_db?characterEncoding=utf-8&useSSL=false&characterSetResults=utf-8&createDatabaseIfNotExist=true
#          driver-class-name: com.mysql.jdbc.Driver
#          username: root
#          password: Admin@1122!
          url: jdbc:mysql://114.247.151.163:3306/test_db?characterEncoding=utf-8&useSSL=false&characterSetResults=utf-8&createDatabaseIfNotExist=true
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          password: Admin@1122!
#          url: jdbc:mysql://localhost:3306/user_local_secondary?characterEncoding=utf-8&useSSL=false&characterSetResults=utf-8&createDatabaseIfNotExist=true
#          driver-class-name: com.mysql.jdbc.Driver
#          username: root
#          password: 111111

#      datasource:
#        driver-class-name: com.mysql.jdbc.Driver
#        username: root
#        password: 111111
#        url: jdbc:mysql://localhost:3306/user_local?characterEncoding=utf-8&useSSL=false&characterSetResults=utf-8&createDatabaseIfNotExist=true
      jpa:
        database: mysql
        database-platform: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
        hibernate:
          ddl-auto: update
        generate-ddl: true
      freemarker:
        suffix: .ftl
        template-loader-path: classpath:/templates
      mvc:
        static-path-pattern: /static/**
#      cache:
#        type: ehcache
#        ehcache:
#          config: ehcache.xml
    server:
      port: 9099
#      ssl:
#        key-store: tomcat.keystore
#        key-store-password: 111111
#        key-store-type: JKS
#        key-alias: tomcat
#        client-auth: want