
    spring:
      datasource:
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 111111
        url: jdbc:mysql://localhost:3306/cmv3_1_local
        type: com.alibaba.druid.pool.DruidDataSource
    server:
      port: 9099